# Generated by Django 5.2.12 on 2026-08-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(default='Business', max_length=20)),
                ('salutation', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('display_name', models.CharField(max_length=150)),
                ('display_name_secondary', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('work_phone', models.CharField(blank=True, max_length=30)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('portal_enabled', models.BooleanField(default=False)),
                ('street_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='Active', max_length=30)),
                ('receivables', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
