# Generated by Django 5.2.12 on 2026-08-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_merchant_product_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='pcs', max_length=30),
        ),
    ]
