# Generated by Django 5.2.12 on 2026-08-18 06:43

from django.db import migrations, models


def normalize_statuses(apps, schema_editor):
    for model_name in ["Customer", "Invoice", "Merchant", "Product"]:
        model = apps.get_model("billing", model_name)
        model.objects.exclude(status__in=["Active", "Inactive"]).update(status="Active")


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30),
        ),
        migrations.RunPython(normalize_statuses, migrations.RunPython.noop),
    ]
