# Generated by Django 5.2.12 on 2026-08-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_customer_status_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('Investment', 'Investment'), ('Withdrawal', 'Withdrawal'), ('Expense', 'Expense')], max_length=30)),
                ('entry_date', models.DateField()),
                ('title', models.CharField(max_length=150)),
                ('party_name', models.CharField(blank=True, max_length=150)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('reference_no', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
    ]
