# Generated by Django 5.2.12 on 2026-08-31 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_pettycashtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('manager_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('module', models.CharField(max_length=80)),
                ('object_name', models.CharField(blank=True, max_length=150)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_number', models.CharField(max_length=50, unique=True)),
                ('quotation_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer')),
            ],
            options={
                'ordering': ['-quotation_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefurbishmentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_no', models.CharField(max_length=50, unique=True)),
                ('model_name', models.CharField(max_length=150)),
                ('serial_no', models.CharField(blank=True, max_length=120)),
                ('configuration', models.CharField(blank=True, max_length=255)),
                ('intake_date', models.DateField()),
                ('qc_technician', models.CharField(blank=True, max_length=120)),
                ('supplier_status', models.CharField(blank=True, max_length=120)),
                ('production_status', models.CharField(choices=[('Intake', 'Device Intake'), ('Checking', 'Checking'), ('Repair', 'Repair'), ('QC', 'QC'), ('Ready', 'Ready for Sale'), ('Scrap', 'Scrap')], default='Intake', max_length=30)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.merchant')),
            ],
            options={
                'ordering': ['-intake_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('stage', models.CharField(max_length=80)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('issue_found', models.CharField(blank=True, max_length=255)),
                ('repair_action', models.TextField(blank=True)),
                ('parts_used', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Hold', 'Hold')], default='Open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='billing.refurbishmentjob')),
            ],
            options={
                'ordering': ['-task_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(max_length=50, unique=True)),
                ('return_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('approval_status', models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Repair', 'Repair'), ('Replacement', 'Replacement'), ('Closed', 'Closed'), ('Rejected', 'Rejected')], default='Requested', max_length=30)),
                ('resolution', models.CharField(blank=True, max_length=120)),
                ('assigned_to', models.CharField(blank=True, max_length=120)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.product')),
            ],
            options={
                'ordering': ['-return_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField()),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.quotation')),
            ],
            options={
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=50, unique=True)),
                ('delivery_date', models.DateField()),
                ('delivered_by', models.CharField(blank=True, max_length=120)),
                ('tracking_no', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.customer')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.salesorder')),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Management', 'Management Full Access'), ('Accountant', 'Accountant'), ('Sales Manager', 'Sales Manager'), ('Sales Staff', 'Sales Staff')], default='Sales Staff', max_length=40)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField()),
                ('movement_type', models.CharField(choices=[('Receive', 'Stock Receiving'), ('Transfer', 'Stock Transfer'), ('Adjustment', 'Stock Adjustment'), ('Issue', 'Stock Issue')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('reference_no', models.CharField(blank=True, max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_out', to='billing.warehouse')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_in', to='billing.warehouse')),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
