# Generated by Django 5.2.12 on 2026-08-31 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_warehouse_auditlog_quotation_refurbishmentjob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.warehouse')),
            ],
            options={
                'ordering': ['warehouse__name', 'product__name'],
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
