from django.urls import path 
from billing import views

urlpatterns = [ 
    path("", views.index, name="index"),
    path("customer", views.customer, name="customer"),
    path("newcustomer", views.newcustomer, name="newcustomer"),
    path("customer/<int:pk>/edit", views.customer_form, name="customer_edit"),
    path("customer/<int:pk>/delete", views.customer_delete, name="customer_delete"),
    path("merchant", views.merchant, name="merchant"),
    path("newmerchant", views.newmerchant, name="newmerchant"),
    path("merchant/<int:pk>/edit", views.merchant_form, name="merchant_edit"),
    path("merchant/<int:pk>/delete", views.merchant_delete, name="merchant_delete"),
    path("products", views.products, name="products"),
    path("products/new", views.product_form, name="product_new"),
    path("products/<int:pk>/edit", views.product_form, name="product_edit"),
    path("products/<int:pk>/delete", views.product_delete, name="product_delete"),
    path("invoice", views.invoice, name="invoice"),
    path("invoice/new", views.invoice_form, name="invoice_new"),
    path("invoice/<int:pk>/edit", views.invoice_form, name="invoice_edit"),
    path("invoice/<int:pk>/preview", views.invoice_preview, name="invoice_preview"),
    path("invoice/<int:pk>/delete", views.invoice_delete, name="invoice_delete"),
    path("investment", views.investment, name="investment"),
    path("investment/new", views.investment_new, name="investment_new"),
    path("investment/<int:pk>/edit", views.investment_edit, name="investment_edit"),
    path("investment/<int:pk>/delete", views.investment_delete, name="investment_delete"),
    path("withdrawal", views.withdrawal, name="withdrawal"),
    path("withdrawal/new", views.withdrawal_new, name="withdrawal_new"),
    path("withdrawal/<int:pk>/edit", views.withdrawal_edit, name="withdrawal_edit"),
    path("withdrawal/<int:pk>/delete", views.withdrawal_delete, name="withdrawal_delete"),
    path("expenses", views.expenses, name="expenses"),
    path("expenses/new", views.expense_new, name="expense_new"),
    path("expenses/<int:pk>/edit", views.expense_edit, name="expense_edit"),
    path("expenses/<int:pk>/delete", views.expense_delete, name="expense_delete"),
    path("petty-cash", views.petty_cash, name="petty_cash"),
    path("petty-cash/new", views.petty_cash_form, name="petty_cash_new"),
    path("petty-cash/<int:pk>/edit", views.petty_cash_form, name="petty_cash_edit"),
    path("petty-cash/<int:pk>/delete", views.petty_cash_delete, name="petty_cash_delete"),
]
